<x-admin::buttons.action_button
    size="xs"
    color="ghost-danger"
    icon="ri-delete-bin-line"
    data-method="delete"
    :data-confirm="__('admin::crud.delete_confirm')"
    :data-action="$renderable->crud()->url($row->getKey())"
    :label="__('admin::crud.delete')"
/>
